"use client";
import { useEffect, useState } from "react";
type Query={id:string;question:string;status:string;priority:string;rule:string;time:string;reason:string};
const seed:Query[]=[
 {id:'EQ-4052',question:'Corresponding author requests switching 1st and 2nd author order during page proof stage without signed COPE form.',status:'Under Lead Review',priority:'Urgent',rule:'AUTHOR-009',time:'42m ago',reason:'Author order change requires the existing approval workflow.'},
 {id:'EQ-4050',question:'Missing given name submitted with incomplete author metadata.',status:'Awaiting Documentation',priority:'High',rule:'AUTHOR-002',time:'2h ago',reason:'Complete author name needs clarification.'},
 {id:'EQ-4048',question:'Dual affiliation with a missing affiliation identifier in XML metadata.',status:'Under Lead Review',priority:'High',rule:'AUTHOR-016',time:'Yesterday 16:15',reason:'Affiliation handling requires lead review.'},
 {id:'EQ-4041',question:'Mononym author requesting omission of the family-name tag in JATS XML.',status:'Resolved',priority:'Normal',rule:'AUTHOR-018',time:'2d ago',reason:'Rule remains incomplete in the current knowledge base.'},
];
export default function QueriesPage(){const [items,setItems]=useState<Query[]>(seed);const [q,setQ]=useState('');const [modal,setModal]=useState(false);const [form,setForm]=useState({question:'',rule:'',priority:'Medium'});useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('ce-queries')||'[]');if(x.length)setItems([...x,...seed].slice(0,12))}catch{}},[]);const shown=items.filter(x=>`${x.id} ${x.question} ${x.rule} ${x.status}`.toLowerCase().includes(q.toLowerCase()));function submit(){if(!form.question.trim())return;const item={id:`EQ-${Date.now().toString().slice(-4)}`,question:form.question,status:'Open',priority:form.priority,rule:form.rule||'Unassigned',time:'Just now',reason:'Submitted by trainee for lead review.'};const next=[item,...items];setItems(next);localStorage.setItem('ce-queries',JSON.stringify(next));setForm({question:'',rule:'',priority:'Medium'});setModal(false)}return <div className="page-wrap"><div className="label-code page-kicker">EDITORIAL INTELLIGENCE · GOVERNANCE &amp; ESCALATION DESK</div><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end'}}><div><h1 className="page-title">Raised Queries</h1><p className="page-subtitle">Manage editorial escalations, ambiguous match decisions, and queries submitted for Lead Editor review.</p></div><button className="ask-btn" onClick={()=>setModal(true)}><span className="material-symbols-outlined">add</span>Raise New Query</button></div>
<div className="query-stats"><Stat label="Logged Volume" value={items.length}/><Stat label="Pending Lead" value={items.filter(x=>x.status!=='Resolved').length}/><Stat label="Attention Required" value={items.filter(x=>x.priority!=='Normal'&&x.status!=='Resolved').length}/><Stat label="Closed Today" value={items.filter(x=>x.status==='Resolved').length}/></div>
<div className="page-toolbar"><div className="search-box"><span className="material-symbols-outlined">search</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search queries by ID, manuscript, subject, or rule..."/></div><select className="filter"><option>All Statuses</option></select><select className="filter"><option>All Priorities</option></select><select className="filter"><option>All Topics</option></select></div>
<div className="query-list">{shown.map(x=><article className="query-card" key={x.id}><div className="query-card-top"><div className="rule-meta"><span className="label-code">#{x.id}</span><span className="label-code">{x.rule}</span><span className="status-pill">{x.priority}</span></div><span className={`status-pill ${x.status==='Resolved'?'status-confirmed':'status-reviewed'}`}>{x.status}</span></div><div className="query-title">{x.question}</div>{x.status==='Resolved'?<div className="query-resolution"><span className="material-symbols-outlined" style={{color:'var(--tertiary)'}}>task_alt</span><div><strong>Resolution Confirmed</strong><div>{x.reason}</div></div></div>:<div className="body-sm" style={{color:'var(--on-surface-variant)'}}>{x.reason}</div>}<div className="query-footer" style={{marginTop:12}}><span>{x.rule} · Raised by trainee · {x.time}</span><button className="primary-outline">View Details</button></div></article>)}</div>
{modal&&<div style={{position:'fixed',inset:0,background:'rgba(28,27,26,.4)',backdropFilter:'blur(5px)',zIndex:100,display:'flex',alignItems:'center',justifyContent:'center',padding:16}}><div style={{width:'100%',maxWidth:640,background:'#fff',borderRadius:12,boxShadow:'0 20px 60px rgba(0,0,0,.18)',overflow:'hidden'}}><div style={{padding:24,background:'var(--surface-container-low)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div className="headline-md"><span className="material-symbols-outlined" style={{color:'var(--primary)',verticalAlign:'middle',marginRight:8}}>contact_support</span>Raise Editorial Query</div><button className="icon-btn" onClick={()=>setModal(false)}><span className="material-symbols-outlined">close</span></button></div><div style={{padding:24}}><label className="field"><span>Query Summary &amp; Author Claim</span><textarea rows={5} value={form.question} onChange={e=>setForm({...form,question:e.target.value})} placeholder="Summarize the discrepancy and guidance required from the lead editor..."/></label><div className="field-row"><label className="field"><span>Priority</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Urgent</option><option>High</option><option>Medium</option><option>Normal</option></select></label><label className="field"><span>Governing Rule</span><input value={form.rule} onChange={e=>setForm({...form,rule:e.target.value})} placeholder="e.g. AUTHOR-009"/></label></div></div><div style={{padding:16,background:'var(--surface-container-low)',display:'flex',justifyContent:'flex-end',gap:8}}><button className="soft-btn" onClick={()=>setModal(false)}>Cancel</button><button className="ask-btn" onClick={submit}>Submit to Lead Review</button></div></div></div>}
</div>}
function Stat({label,value}:{label:string,value:number}){return <div className="stat-card"><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>}
